### ISSUE TITLE
Add Cargo.lock to repository

### ISSUE THREAD

**Issue by jirutka** [tembo-io/prometheus_fdw#5]
Can you please add Cargo.lock to the repository and keep it up to date for releases? It’s needed for reproducible builds, which is especially important for Linux distributions. With no lockfile, cargo fetches the latest version of the dependencies that satisfy the version constraint, so you may get a different binary when it’s built a week later.

**Comment by Jayko001** [comment]
https://github.com/tembo-io/prometheus_fdw/pull/9 adds cargo.lock. Thank you for creating a issue for it.
